name: urna_eletronica
description: Simulador de Urna Eletrônica Digital.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.10.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.9
  another_flushbar: ^2.2.4
  animated_text_kit: ^4.3.0
  audioplayers: ^6.1.0
  sqflite: ^2.3.3
  path_provider: ^2.1.2
  csv: ^6.0.0
  share_plus: ^9.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.14.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/brasao.png
    - assets/images/vereador.png
    - assets/images/prefeito.png
    - assets/som.mp3
    - assets/images/vereador/saldanha.jpg
    - assets/images/vereador/pt.jpg
    - assets/images/vereador/tucano.jpg
    - assets/images/prefeito/naumir.jpg
    - assets/images/prefeito/vice.jpg
    - assets/images/prefeito/pt.jpg
    - assets/images/prefeito/tucano.jpg
    - assets/images/eleicoes2026/
    - assets/json/vereador.json
    - assets/json/prefeito.json
    - assets/json/deputado_federal.json
    - assets/json/deputado_estadual.json
    - assets/json/senador.json
    - assets/json/governador.json
    - assets/csv/presevice_novo.csv
    - assets/csv/govsendep_novo.csv
    - assets/icons/

flutter_launcher_icons:
  android: true
  ios: true
  image_path: 'assets/icons/logo_app.png'
  remove_alpha_ios: true
  adaptive_icon_background: '#ffffff'
  adaptive_icon_foreground: 'assets/icons/logo_app.png'
